apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev
agents: 1
registries:
  use:
    - k3d-registry.localhost:5000
volumes:
  - volume: /home/nickguerra/.ollama:/home/nickguerra/.ollama
    nodeFilters:
      - all